const DE = {
  all: "Alle",
  filter: "Nach Status und Spezies filtern",
  name: "Name",
  gender: "Geschlecht",
  origin: "Herkunft",
  status: "Status",
  species: "Spezies",
  alive: "Lebendig",
  dead: "Tot",
  unknown: "Unbekannt",
  human: "Mensch",
  alien: "Außerirdischer",
  characters: "Charaktere",
  loading: "Wird geladen",
  enableScroll: "Unendliches Scrollen aktivieren",
  load: "Mehr laden",
  male: "Männlich",
  female: "Weiblich",
  myth: "Mythologische Kreatur",
  animal: "Tier",
  robot: "Roboter",
  allSpecies: "Alle Spezies",
  filterByStatus: "Filter nach Status",
  filterBySpecies: "Filter nach Spezies",
};

export default DE;
